---
name: Microsoft Defender for Devops
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        description: .NET version to use
        # renovate: datasource=dotnet-version depName=dotnet-sdk
        default: "8.0.422"
      runs-on:
        required: false
        type: string
        description: Runner to use
        default: windows-latest
permissions:
  contents: read
  security-events: write
jobs:
  msdo:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68  # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@08976cb623803b1b36d7112d4ff9f59eae704de0  # v1.12.0
        id: msdo
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@d1ba80a13dd99fba24a470575428917156a28b43  # v4.37.5
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
